<?php

declare(strict_types=1);

namespace Nene2\Conformance;

/**
 * Per-repo suppression store, loaded from `conformance.baseline.json`.
 *
 * Two complementary mechanisms let a repo adopt the linter gradually while
 * keeping *new* drift red:
 *
 *   - **allow** — a human-curated allowlist. Each entry is keyed by
 *     `(rule, file)` and MUST carry a non-empty `reason`; a missing reason is a
 *     hard configuration error (the linter refuses to run) so the list stays
 *     auditable. Suppresses every finding of that rule in that file.
 *   - **ignore** — a PHPStan-baseline-shaped snapshot, keyed by
 *     `(rule, file, message)` with a `count`. Generated by `--write-baseline`,
 *     it captures existing drift so only newly-introduced findings fail. Matching
 *     ignores line numbers so it survives unrelated edits.
 *
 * File shape:
 * ```json
 * {
 *   "version": 1,
 *   "allow":  [ { "rule": "D4", "file": "src/Foo.php", "reason": "why" } ],
 *   "ignore": [ { "rule": "D4", "file": "src/Bar.php", "message": "...", "count": 2 } ]
 * }
 * ```
 */
final class Baseline
{
    /** @var list<array{rule: string, file: string, reason: string}> */
    private array $allow;

    /** @var array<string, int> remaining ignore budget keyed by finding identity */
    private array $ignoreBudget;

    /** @var list<string> */
    private array $validationErrors;

    /**
     * @param list<array{rule: string, file: string, reason: string}> $allow
     * @param array<string, int>                                       $ignoreBudget
     * @param list<string>                                             $validationErrors
     */
    private function __construct(array $allow, array $ignoreBudget, array $validationErrors)
    {
        $this->allow = $allow;
        $this->ignoreBudget = $ignoreBudget;
        $this->validationErrors = $validationErrors;
    }

    public static function empty(): self
    {
        return new self([], [], []);
    }

    public static function load(string $path): self
    {
        if (!is_file($path)) {
            return self::empty();
        }

        $raw = @file_get_contents($path);

        if ($raw === false) {
            return new self([], [], ["Could not read baseline file: {$path}"]);
        }

        $decoded = json_decode($raw, true);

        if (!is_array($decoded)) {
            return new self([], [], ["Baseline file is not valid JSON: {$path}"]);
        }

        $errors = [];
        $allow = [];

        foreach (self::rows($decoded, 'allow') as $index => $row) {
            $rule = is_string($row['rule'] ?? null) ? $row['rule'] : '';
            $file = is_string($row['file'] ?? null) ? $row['file'] : '';
            $reason = is_string($row['reason'] ?? null) ? trim($row['reason']) : '';

            if ($rule === '' || $file === '') {
                $errors[] = "baseline allow[{$index}]: 'rule' and 'file' are required.";
                continue;
            }

            if ($reason === '') {
                $errors[] = "baseline allow[{$index}] ({$rule} {$file}): a non-empty 'reason' is required.";
                continue;
            }

            $allow[] = ['rule' => $rule, 'file' => $file, 'reason' => $reason];
        }

        $ignoreBudget = [];

        foreach (self::rows($decoded, 'ignore') as $index => $row) {
            $rule = is_string($row['rule'] ?? null) ? $row['rule'] : '';
            $file = is_string($row['file'] ?? null) ? $row['file'] : '';
            $message = is_string($row['message'] ?? null) ? $row['message'] : '';
            $count = is_int($row['count'] ?? null) ? $row['count'] : 1;

            if ($rule === '' || $file === '' || $message === '') {
                $errors[] = "baseline ignore[{$index}]: 'rule', 'file' and 'message' are required.";
                continue;
            }

            $key = $rule . "\0" . $file . "\0" . $message;
            $ignoreBudget[$key] = ($ignoreBudget[$key] ?? 0) + max(1, $count);
        }

        return new self($allow, $ignoreBudget, $errors);
    }

    /**
     * @return list<string>
     */
    public function validationErrors(): array
    {
        return $this->validationErrors;
    }

    /**
     * The curated allowlist entries, preserved verbatim when regenerating the
     * baseline snapshot.
     *
     * @return list<array{rule: string, file: string, reason: string}>
     */
    public function allowEntries(): array
    {
        return $this->allow;
    }

    /**
     * Whether a finding is suppressed by this baseline. Consumes ignore budget so
     * a baseline of `count: 1` only masks a single occurrence.
     */
    public function suppresses(Finding $finding): bool
    {
        foreach ($this->allow as $entry) {
            if ($entry['rule'] === $finding->ruleId && $entry['file'] === $finding->file) {
                return true;
            }
        }

        $key = $finding->identity();

        if (($this->ignoreBudget[$key] ?? 0) > 0) {
            $this->ignoreBudget[$key]--;

            return true;
        }

        return false;
    }

    /**
     * @param array<string, mixed> $decoded
     * @return array<int, array<string, mixed>>
     */
    private static function rows(array $decoded, string $key): array
    {
        $rows = $decoded[$key] ?? null;

        if (!is_array($rows)) {
            return [];
        }

        $result = [];

        foreach (array_values($rows) as $index => $row) {
            if (is_array($row)) {
                $result[$index] = $row;
            }
        }

        return $result;
    }
}
