<?php

declare(strict_types=1);

namespace Nene2\Database;

/**
 * Executes parameterised SQL queries against the database connection.
 *
 * Implement this interface to swap the persistence backend (e.g. SQLite for tests,
 * MySQL for production) without changing repository code.
 *
 * Part of the public API stability guarantee (see ADR 0009).
 *
 * @phpstan-type SqlParameter string|int|float|bool|null
 * @phpstan-type SqlParameters array<string|int, SqlParameter>
 * @phpstan-type SqlRow array<string, mixed>
 */
interface DatabaseQueryExecutorInterface
{
    /**
     * @param SqlParameters $parameters
     */
    public function execute(string $sql, array $parameters = []): int;

    /**
     * Returns the ID generated by the last INSERT statement.
     *
     * Works correctly for **SQLite** and **MySQL/MariaDB**.
     *
     * **PostgreSQL**: `PDO::lastInsertId()` returns an empty string when called without a
     * sequence name, so this method returns `0` on PostgreSQL. Instead, append `RETURNING id`
     * to your INSERT SQL and call {@see fetchOne()} to retrieve the generated ID in a single
     * round trip:
     *
     * ```php
     * $row = $executor->fetchOne(
     *     'INSERT INTO reviews (title, rating) VALUES (?, ?) RETURNING id',
     *     [$title, $rating],
     * );
     * $id = (int) ($row['id'] ?? 0);
     * ```
     *
     * See `docs/howto/use-postgresql.md` for the complete pattern.
     */
    public function lastInsertId(): int;

    /**
     * @param SqlParameters $parameters
     * @return SqlRow|null
     */
    public function fetchOne(string $sql, array $parameters = []): ?array;

    /**
     * @param SqlParameters $parameters
     * @return list<SqlRow>
     */
    public function fetchAll(string $sql, array $parameters = []): array;
}
