<?php

/**
 * Regenerates the data-driven howto indexes so they stay in sync with the
 * files on disk:
 *
 * - English (`docs/howto`): a "Browse by category" index built from each
 *   guide's YAML frontmatter (every guide, grouped into the seven categories),
 *   injected between the AUTO-INDEX markers in README.md, plus a `by-tag.md`
 *   page grouping guides by tag.
 * - Other locales: a flat, alphabetical "Full Index" built from each guide's
 *   `# H1` (translations carry no frontmatter), injected into README.md.
 *
 * The manual curation in each README (the "I want to…" finder table) is left
 * untouched; only the content between the AUTO-INDEX markers is regenerated.
 *
 * Usage: php tools/build-howto-index.php
 */

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Yaml\Yaml;

$root = dirname(__DIR__);

const AUTO_INDEX_START = '<!-- AUTO-INDEX:START (generated by `composer howto:index` — do not edit by hand) -->';
const AUTO_INDEX_END   = '<!-- AUTO-INDEX:END -->';

/** Files in a howto directory that are indexes, not guides. */
const NON_GUIDE_FILES = ['README.md', 'by-tag.md'];

/**
 * Category slug → display label, in the order they should appear.
 *
 * @var array<string, string>
 */
const CATEGORY_LABELS = [
    'getting-started' => 'Getting Started',
    'auth'            => 'Authentication & Authorization',
    'security'        => 'Security',
    'database'        => 'Database',
    'api-design'      => 'API Design',
    'infrastructure'  => 'Background & Infrastructure',
    'product'         => 'Product Features',
];

/**
 * Locale howto directories (relative to the repository root) and the localized
 * strings used when (re)generating their flat index section.
 *
 * @var array<string, array{dir: string, h1: string, heading: string, note: string}>
 */
$locales = [
    'en' => [
        'dir'     => 'docs/howto',
        'h1'      => 'Howto Guides Index',
        'heading' => 'Browse by category',
        'note'    => '',
    ],
    'ja' => [
        'dir'     => 'docs/ja/howto',
        'h1'      => 'HOWTO ガイド索引',
        'heading' => '全索引（自動生成）',
        'note'    => 'このディレクトリの全ガイド（ファイル名順）。`composer howto:index` で再生成する。',
    ],
    'fr' => [
        'dir'     => 'docs/fr/howto',
        'h1'      => 'Index des guides pratiques',
        'heading' => 'Index complet (généré automatiquement)',
        'note'    => 'Tous les guides de ce répertoire, triés par nom de fichier. Régénérer avec `composer howto:index`.',
    ],
    'zh' => [
        'dir'     => 'docs/zh/howto',
        'h1'      => '操作指南索引',
        'heading' => '完整索引（自动生成）',
        'note'    => '本目录中的全部指南（按文件名排序）。使用 `composer howto:index` 重新生成。',
    ],
    'de' => [
        'dir'     => 'docs/de/howto',
        'h1'      => 'Anleitungsindex',
        'heading' => 'Vollständiger Index (automatisch generiert)',
        'note'    => 'Alle Anleitungen in diesem Verzeichnis, nach Dateiname sortiert. Mit `composer howto:index` neu generieren.',
    ],
    'pt-br' => [
        'dir'     => 'docs/pt-br/howto',
        'h1'      => 'Índice de guias práticos',
        'heading' => 'Índice completo (gerado automaticamente)',
        'note'    => 'Todos os guias deste diretório, ordenados por nome de arquivo. Regenere com `composer howto:index`.',
    ],
];

/**
 * @return list<string> Guide file paths in a howto directory (excludes indexes).
 */
function guideFiles(string $dir): array
{
    $files = glob($dir . '/*.md') ?: [];
    $files = array_filter($files, static fn (string $f): bool => !in_array(basename($f), NON_GUIDE_FILES, true));
    sort($files, SORT_STRING);

    return $files;
}

/**
 * Extract the first level-1 heading from a Markdown file, falling back to the
 * file name (without extension) when none is found.
 */
function howtoTitle(string $path): string
{
    foreach (preg_split('/\r?\n/', (string) file_get_contents($path)) ?: [] as $line) {
        if (preg_match('/^#\s+(.+?)\s*$/', $line, $m) === 1) {
            return $m[1];
        }
    }

    return basename($path, '.md');
}

/**
 * Parse the YAML frontmatter of a guide, or null when it has none.
 *
 * @return array<string, mixed>|null
 */
function readFrontmatter(string $path): ?array
{
    $contents = (string) file_get_contents($path);
    if (preg_match('/^---\r?\n(.*?)\r?\n---\r?\n/s', $contents, $m) !== 1) {
        return null;
    }
    $parsed = Yaml::parse($m[1]);

    return is_array($parsed) ? $parsed : null;
}

/**
 * Escape a Markdown table cell.
 */
function cell(string $value): string
{
    return str_replace('|', '\\|', $value);
}

/**
 * Build the flat alphabetical index used for locales without frontmatter.
 *
 * @param array{heading: string, note: string} $locale
 */
function flatIndexInner(string $dir, array $locale): string
{
    $rows = [];
    foreach (guideFiles($dir) as $file) {
        $name = basename($file);
        $rows[] = '| [' . $name . '](' . $name . ') | ' . cell(howtoTitle($file)) . ' |';
    }

    return '## ' . $locale['heading'] . "\n\n"
        . $locale['note'] . "\n\n"
        . "| Guide | Title |\n|---|---|\n" . implode("\n", $rows);
}

/**
 * Build the "Browse by category" index from frontmatter (English).
 *
 * @return array{inner: string, missing: list<string>}
 */
function categoryBrowseInner(string $dir): array
{
    /** @var array<string, list<array{slug: string, title: string, difficulty: string, tags: list<string>}>> $byCategory */
    $byCategory = [];
    $missing    = [];

    foreach (guideFiles($dir) as $file) {
        $slug = basename($file, '.md');
        $fm   = readFrontmatter($file);
        if ($fm === null || !isset($fm['category'])) {
            $missing[] = basename($file);
            continue;
        }
        /** @var list<string> $tags */
        $tags = array_map('strval', is_array($fm['tags'] ?? null) ? $fm['tags'] : []);
        $byCategory[(string) $fm['category']][] = [
            'slug'       => $slug,
            'title'      => is_string($fm['title'] ?? null) ? $fm['title'] : $slug,
            'difficulty' => is_string($fm['difficulty'] ?? null) ? $fm['difficulty'] : '',
            'tags'       => $tags,
        ];
    }

    $sections = [
        '## Browse by category',
        'Auto-generated from each guide\'s frontmatter (`category` / `difficulty` / `tags`); lists every guide. '
            . 'See also [Browse by tag](by-tag.md). Regenerate with `composer howto:index`.',
    ];

    foreach (CATEGORY_LABELS as $slug => $label) {
        $guides = $byCategory[$slug] ?? [];
        if ($guides === []) {
            continue;
        }
        usort($guides, static fn (array $a, array $b): int => strcasecmp($a['title'], $b['title']));

        $rows = [];
        foreach ($guides as $g) {
            $tagList = implode(' ', array_map(static fn (string $t): string => '`' . $t . '`', $g['tags']));
            $rows[]  = '| [' . cell($g['title']) . '](' . $g['slug'] . '.md) | ' . $g['difficulty'] . ' | ' . $tagList . ' |';
        }

        $sections[] = '### ' . $label . ' (' . count($guides) . ")\n\n"
            . "| Guide | Difficulty | Tags |\n|---|---|---|\n" . implode("\n", $rows);
    }

    return ['inner' => implode("\n\n", $sections), 'missing' => $missing];
}

/**
 * Build the full by-tag browse page (English).
 */
function byTagPage(string $dir): string
{
    /** @var array<string, list<array{slug: string, title: string}>> $byTag */
    $byTag = [];

    foreach (guideFiles($dir) as $file) {
        $fm = readFrontmatter($file);
        if ($fm === null || !is_array($fm['tags'] ?? null)) {
            continue;
        }
        $slug  = basename($file, '.md');
        $title = is_string($fm['title'] ?? null) ? $fm['title'] : $slug;
        foreach ($fm['tags'] as $tag) {
            $byTag[(string) $tag][] = ['slug' => $slug, 'title' => $title];
        }
    }

    ksort($byTag, SORT_STRING);

    $sections = [
        '# Browse Howto Guides by Tag',
        'Auto-generated from each guide\'s frontmatter `tags`. Regenerate with `composer howto:index`. '
            . 'For the category view see the [howto index](README.md).',
    ];

    foreach ($byTag as $tag => $guides) {
        usort($guides, static fn (array $a, array $b): int => strcasecmp($a['title'], $b['title']));
        $items = array_map(
            static fn (array $g): string => '- [' . $g['title'] . '](' . $g['slug'] . '.md)',
            $guides,
        );
        $sections[] = '## `' . $tag . '` (' . count($guides) . ")\n\n" . implode("\n", $items);
    }

    return implode("\n\n", $sections) . "\n";
}

/**
 * Wrap generated inner Markdown between the AUTO-INDEX markers.
 */
function wrapSection(string $inner): string
{
    return AUTO_INDEX_START . "\n\n" . $inner . "\n\n" . AUTO_INDEX_END;
}

/**
 * Strip trailing horizontal-rule lines and surrounding whitespace so the
 * separator the generator adds never accumulates across runs.
 */
function trimTrailingRule(string $body): string
{
    return rtrim((string) preg_replace('/(\s*\n-{3,}[ \t]*)+\s*$/', '', $body));
}

/**
 * Insert or replace the auto-index section inside a README body. Idempotent:
 * the manual content before the markers and any content after them are kept
 * verbatim, and re-running produces byte-identical output.
 */
function injectSection(string $body, string $section): string
{
    $startPos = strpos($body, AUTO_INDEX_START);
    $endPos   = strpos($body, AUTO_INDEX_END);

    if ($startPos !== false && $endPos !== false && $endPos > $startPos) {
        $before = substr($body, 0, $startPos);
        $after  = substr($body, $endPos + strlen(AUTO_INDEX_END));
    } else {
        $before = $body;
        $after  = '';
    }

    $before = trimTrailingRule($before);
    $after  = ltrim($after);

    $head = $before === '' ? '' : $before . "\n\n---\n\n";
    $tail = $after === '' ? "\n" : "\n\n" . $after . "\n";

    return $head . $section . $tail;
}

// -------------------------------------------------------------------------
// Generate / update each locale README (+ the English by-tag page)
// -------------------------------------------------------------------------

$written = 0;

foreach ($locales as $code => $locale) {
    $dir = $root . '/' . $locale['dir'];
    if (!is_dir($dir)) {
        echo "Skipped {$code}: {$locale['dir']} not found\n";
        continue;
    }

    if ($code === 'en') {
        ['inner' => $inner, 'missing' => $missing] = categoryBrowseInner($dir);
        if ($missing !== []) {
            echo 'Warning: guides without frontmatter skipped from category browse: '
                . implode(', ', $missing) . "\n";
        }

        $byTagPath = $dir . '/by-tag.md';
        file_put_contents($byTagPath, byTagPage($dir));
        echo "Written: {$locale['dir']}/by-tag.md\n";
    } else {
        $inner = flatIndexInner($dir, $locale);
    }

    $section    = wrapSection($inner);
    $readmePath = $dir . '/README.md';
    $body       = is_file($readmePath)
        ? (string) file_get_contents($readmePath)
        : '# ' . $locale['h1'] . "\n";

    file_put_contents($readmePath, injectSection($body, $section));
    echo "Written: {$locale['dir']}/README.md\n";
    $written++;
}

echo "Done: {$written} locale index file(s) updated.\n";
