<?php

/**
 * Generates a flat, auto-generated "Full Index" of every howto guide for each
 * locale, keeping it in sync with the files actually present on disk.
 *
 * The manual curation in each README (the "I want to…" finder table and the
 * category tables) is left untouched. Only the content between the
 * AUTO-INDEX markers is regenerated.
 *
 * Usage: php tools/build-howto-index.php
 */

declare(strict_types=1);

$root = dirname(__DIR__);

const AUTO_INDEX_START = '<!-- AUTO-INDEX:START (generated by `composer howto:index` — do not edit by hand) -->';
const AUTO_INDEX_END   = '<!-- AUTO-INDEX:END -->';

/**
 * Locale howto directories (relative to the repository root) and the
 * localized strings used when (re)generating their index section.
 *
 * @var array<string, array{dir: string, h1: string, heading: string, note: string}>
 */
$locales = [
    'en' => [
        'dir'     => 'docs/howto',
        'h1'      => 'Howto Guides Index',
        'heading' => 'Full Index (auto-generated)',
        'note'    => 'Every guide in this directory, sorted by file name. Regenerate with `composer howto:index`.',
    ],
    'ja' => [
        'dir'     => 'docs/ja/howto',
        'h1'      => 'HOWTO ガイド索引',
        'heading' => '全索引（自動生成）',
        'note'    => 'このディレクトリの全ガイド（ファイル名順）。`composer howto:index` で再生成する。',
    ],
    'fr' => [
        'dir'     => 'docs/fr/howto',
        'h1'      => 'Index des guides pratiques',
        'heading' => 'Index complet (généré automatiquement)',
        'note'    => 'Tous les guides de ce répertoire, triés par nom de fichier. Régénérer avec `composer howto:index`.',
    ],
    'zh' => [
        'dir'     => 'docs/zh/howto',
        'h1'      => '操作指南索引',
        'heading' => '完整索引（自动生成）',
        'note'    => '本目录中的全部指南（按文件名排序）。使用 `composer howto:index` 重新生成。',
    ],
    'de' => [
        'dir'     => 'docs/de/howto',
        'h1'      => 'Anleitungsindex',
        'heading' => 'Vollständiger Index (automatisch generiert)',
        'note'    => 'Alle Anleitungen in diesem Verzeichnis, nach Dateiname sortiert. Mit `composer howto:index` neu generieren.',
    ],
    'pt-br' => [
        'dir'     => 'docs/pt-br/howto',
        'h1'      => 'Índice de guias práticos',
        'heading' => 'Índice completo (gerado automaticamente)',
        'note'    => 'Todos os guias deste diretório, ordenados por nome de arquivo. Regenere com `composer howto:index`.',
    ],
];

/**
 * Extract the first level-1 heading from a Markdown file, falling back to the
 * file name (without extension) when none is found.
 */
function howtoTitle(string $path): string
{
    $handle = fopen($path, 'r');
    if ($handle === false) {
        return basename($path, '.md');
    }
    $title = null;
    while (($line = fgets($handle)) !== false) {
        if (preg_match('/^#\s+(.+?)\s*$/', $line, $m) === 1) {
            $title = $m[1];
            break;
        }
    }
    fclose($handle);

    return $title ?? basename($path, '.md');
}

/**
 * Build the Markdown table listing every howto guide in a directory.
 *
 * @return array{count: int, table: string}
 */
function buildIndexTable(string $dir): array
{
    $files = glob($dir . '/*.md') ?: [];
    $files = array_filter($files, static fn (string $f): bool => basename($f) !== 'README.md');
    sort($files, SORT_STRING);

    $rows = [];
    foreach ($files as $file) {
        $name  = basename($file);
        $title = str_replace('|', '\\|', howtoTitle($file));
        $rows[] = "| [{$name}]({$name}) | {$title} |";
    }

    $table = "| Guide | Title |\n|---|---|\n" . implode("\n", $rows);

    return ['count' => count($files), 'table' => $table];
}

/**
 * Render the full auto-index section (between and including the markers).
 *
 * @param array{dir: string, h1: string, heading: string, note: string} $locale
 */
function renderSection(array $locale, int $count, string $table): string
{
    $note = str_replace('{count}', (string) $count, $locale['note']);

    return AUTO_INDEX_START . "\n\n"
        . '## ' . $locale['heading'] . "\n\n"
        . $note . "\n\n"
        . $table . "\n\n"
        . AUTO_INDEX_END;
}

/**
 * Strip trailing horizontal-rule lines and surrounding whitespace so the
 * separator the generator adds never accumulates across runs.
 */
function trimTrailingRule(string $body): string
{
    return rtrim((string) preg_replace('/(\s*\n-{3,}[ \t]*)+\s*$/', '', $body));
}

/**
 * Insert or replace the auto-index section inside a README body. Idempotent:
 * the manual content before the markers and any content after them are kept
 * verbatim, and re-running produces byte-identical output.
 */
function injectSection(string $body, string $section): string
{
    $startPos = strpos($body, AUTO_INDEX_START);
    $endPos   = strpos($body, AUTO_INDEX_END);

    if ($startPos !== false && $endPos !== false && $endPos > $startPos) {
        $before = substr($body, 0, $startPos);
        $after  = substr($body, $endPos + strlen(AUTO_INDEX_END));
    } else {
        // No markers yet: the whole body is manual content; append after it.
        $before = $body;
        $after  = '';
    }

    $before = trimTrailingRule($before);
    $after  = ltrim($after);

    $head = $before === '' ? '' : $before . "\n\n---\n\n";
    $tail = $after === '' ? "\n" : "\n\n" . $after . "\n";

    return $head . $section . $tail;
}

// -------------------------------------------------------------------------
// Generate / update each locale README
// -------------------------------------------------------------------------

$written = 0;

foreach ($locales as $code => $locale) {
    $dir = $root . '/' . $locale['dir'];
    if (!is_dir($dir)) {
        echo "Skipped {$code}: {$locale['dir']} not found\n";
        continue;
    }

    ['count' => $count, 'table' => $table] = buildIndexTable($dir);
    $section = renderSection($locale, $count, $table);

    $readmePath = $dir . '/README.md';
    if (is_file($readmePath)) {
        $body = (string) file_get_contents($readmePath);
    } else {
        // Locales without a curated README get an index-only README so the
        // VitePress sidebar link (`<lang>/howto/README`) resolves.
        $body = '# ' . $locale['h1'] . "\n";
    }

    $updated = injectSection($body, $section);
    file_put_contents($readmePath, $updated);
    echo sprintf("Written: %s/README.md (%d guides)\n", $locale['dir'], $count);
    $written++;
}

echo "Done: {$written} locale index file(s) updated.\n";
